## To build and run the image run:
## docker compose up -d

version: "3.8"
services:
  mojo :
    container_name: mojo
    build :
      context: .
      dockerfile: Dockerfile
      args:
        - AUTH_KEY=1Auth_token
      no_cache : true
    ports:
      - 8888:8888 

    volumes:
      - ./..:/mojo
      
    working_dir: /mojo 
    